### ISSUE TITLE
I need help 😞 

### ISSUE THREAD

**Issue by the-maty** [Simon536/pi-tailscale-stack#1]
Hello,
I tried to do what were you writing in readme and container was up and running, but nothing was shoving on tailscale. Yes I did SECRET_AUTH_KEY env and looks like I did not miss anything what were you typing in readme 😢.

Could you please guide me in more detailed way? I am really excited to get this working on my RPi 😃

**Comment by Simon536** [comment]
I have added some screenshots to the readme, which might help you.

Are you running the same versions of Docker and Portainer as I am? I haven't tested this setup on any other versions. The other thing that I would recommend checking is whether your auth key is reusable.

**Comment by the-maty** [comment]
I am using the same version.
Maybe my problem is that reuseable thing, that I did not turn on. Gonna try to check and copy your setup.
I will let you know, how it ended.
Thanks for helping me.

**Comment by the-maty** [comment]
Looks from the log, that problem is somewhere else.

2022/03/29 18:04:58 Switching ipn state NoState -> NeedsLogin (WantRunning=false, nm=false)

2022/03/29 18:04:58 blockEngineUpdates(true)

2022/03/29 18:04:58 health("overall"): error: state=NeedsLogin, wantRunning=false

2022/03/29 18:04:58 wgengine: Reconfig: configuring userspace wireguard config (with 0/0 peers)

2022/03/29 18:04:58 wgengine: Reconfig: configuring router

2022/03/29 18:04:58 wgengine: Reconfig: configuring DNS

2022/03/29 18:04:58 dns: Set: {DefaultResolvers:[] Routes:{} SearchDomains:[] Hosts:0}

2022/03/29 18:04:58 dns: Resolvercfg: {Routes:{} Hosts:0 LocalDomains:[]}

2022/03/29 18:04:58 dns: OScfg: {Nameservers:[] SearchDomains:[] MatchDomains:[]}

2022/03/29 18:04:58 router: somebody (likely systemd-networkd) deleted ip rules; restoring Tailscale's

**Comment by Simon536** [comment]
Ok, I deleted my stack and went through the process again. I ended up with the same issue as you, but I managed to solve it.

1. Remove your tailscale stack in Portainer.
2. Remove any tailscale images in Portainer. This is because the key is stored in the image, and Portainer won't create a new image unless we remove the old ones.
3. Login to Tailscale and create a new key that is reusable and pre-authorized.
4. Add a new tailscale stack using this key.
5. Check the log on the new container. You should find a line that starts like this: `control: AuthURL is https://login.tailscale.com/a/`
Follow that link to authorise your device on the tailnet. I'm pretty sure you aren't supposed to have to do this step with a pre-authorized key, but it seems like it is necessary.

Let me know if that solves the issue for you. Not sure if Tailscale has changed how authentication works recently, because I didn't have to follow this process last time I set this up.

**Comment by the-maty** [comment]
I have done everything you said and still experiencing the same issue 😢 
EDIT: It is little bit different tbh, but still doesnt work
BTW **I dont** see in logs --> `control: AuthURL is https://login.tailscale.com/a/` 😩

**Comment by the-maty** [comment]
I dont know if its safe to just upload my log to provide more in depth info about my issue 😕
